// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvq22yfsMO4WvyLaJqmX6xxaU3eTeonwU',
    appId: '1:163123245310:web:c298e8b8f784472cc335af',
    messagingSenderId: '163123245310',
    projectId: 'e-commerce-27ef9',
    authDomain: 'e-commerce-27ef9.firebaseapp.com',
    storageBucket: 'e-commerce-27ef9.appspot.com',
    measurementId: 'G-EQEX3GE9V5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf_Lt-fl6mKIbwkf1lPOG9o_HT6qIqf9k',
    appId: '1:163123245310:android:5ab7b98f105341e0c335af',
    messagingSenderId: '163123245310',
    projectId: 'e-commerce-27ef9',
    storageBucket: 'e-commerce-27ef9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjTA9WG4PLp3MqbmojiT40G0IT5yLJrvY',
    appId: '1:163123245310:ios:dbac0b312eb1f9c7c335af',
    messagingSenderId: '163123245310',
    projectId: 'e-commerce-27ef9',
    storageBucket: 'e-commerce-27ef9.appspot.com',
    iosBundleId: 'com.example.finalExamOnlineShoping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjTA9WG4PLp3MqbmojiT40G0IT5yLJrvY',
    appId: '1:163123245310:ios:a04e0938206fe4a5c335af',
    messagingSenderId: '163123245310',
    projectId: 'e-commerce-27ef9',
    storageBucket: 'e-commerce-27ef9.appspot.com',
    iosBundleId: 'com.example.finalExamOnlineShoping.RunnerTests',
  );
}
